module.exports = {
  extends: [
    "stylelint-config-standard",
    "stylelint-config-css-modules",
    "stylelint-config-rational-order",
    "stylelint-config-prettier",
    "stylelint-no-unsupported-browser-features",
  ],
  plugins: ["stylelint-declaration-block-no-ignored-properties"],
  rules: {
    "function-url-quotes": "always",
    "plugin/declaration-block-no-ignored-properties": true,
    "unit-no-unknown": [true, { ignoreUnits: ["rpx"] }],
    "prettier/prettier": true,
    "value-list-max-empty-lines": null,
    "declaration-block-no-duplicate-properties": null,
    "no-empty-source": null,
    "font-family-no-missing-generic-family-keyword": null,
    "selector-pseudo-class-no-unknown": null,
    "block-no-empty": null,
    "function-calc-no-invalid": null,
    "no-descending-specificity": null,
    "no-duplicate-selectors": null,
    "declaration-colon-newline-after": null,
    "selector-type-no-unknown": null,
  },
  ignoreFiles: ["**/*.js", "**/*.jsx", "**/*.tsx", "**/*.ts"],
};
